In [1]:
import pandas as pd

In [44]:
# Load the dataset
df = pd.read_excel('Train/Belt 1 9 Months negative data.xlsx')
#df = pd.read_excel('Test/Belt Sample Data.xlsx')
df

,Name,Timestamp,Status,Description,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition
0,Conveyor Belt 4,2025-08-15 00:00:00,Running,NaN,1490.82,0.04,77.130,96.902,1.36,318.07,55.12,15.79,382.09,1.58000,86.000
1,Conveyor Belt 4,2025-08-15 00:15:00,Running,NaN,1498.37,0.04,77.076,96.975,1.07,295.50,59.68,14.34,376.48,1.57950,85.854
2,Conveyor Belt 4,2025-08-15 00:30:00,Running,NaN,1503.22,0.06,77.307,96.755,1.21,314.38,58.20,15.03,384.20,1.57925,85.781
3,Conveyor Belt 4,2025-08-15 00:45:00,Running,NaN,1508.11,0.04,77.474,97.661,1.29,311.84,56.16,15.43,379.79,1.57900,85.708
4,Conveyor Belt 4,2025-08-15 01:00:00,Running,NaN,1498.13,0.06,77.785,97.471,1.07,317.14,55.39,14.35,383.95,1.57875,85.635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26204,Conveyor Belt 4,2026-05-13 23:00:00,Running,NaN,1502.84,0.05,76.119,95.287,1.39,305.42,62.72,15.93,377.00,1.63700,68.610
26205,Conveyor Belt 4,2026-05-13 23:15:00,Running,NaN,1503.36,0.05,75.889,95.888,1.06,312.37,64.70,14.28,377.08,1.63675,68.537
26206,Conveyor Belt 4,2026-05-13 23:30:00,Running,NaN,1498.34,0.04,76.001,95.738,1.28,287.36,57.81,15.42,384.19,1.63650,68.464
26207,Conveyor Belt 4,2026-05-13 23:45:00,Running,NaN,1495.26,0.05,76.106,95.848,1.30,297.35,58.84,15.49,376.62,1.63625,68.391
26208,Conveyor Belt 4,2026-05-14 00:00:00,Running,NaN,1490.82,0.04,77.130,96.902,1.36,318.07,55.12,15.79,382.09,1.58000,68.318

In [45]:
# Convert 'Timestamp' to datetime, invalid dates will be set to NaT
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce') 

# Drop rows where the 'Timestamp' is NaT (invalid date)
df.dropna(subset=['Timestamp'], inplace=True)

df

,Name,Timestamp,Status,Description,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition
0,Conveyor Belt 4,2025-08-15 00:00:00,Running,NaN,1490.82,0.04,77.130,96.902,1.36,318.07,55.12,15.79,382.09,1.58000,86.000
1,Conveyor Belt 4,2025-08-15 00:15:00,Running,NaN,1498.37,0.04,77.076,96.975,1.07,295.50,59.68,14.34,376.48,1.57950,85.854
2,Conveyor Belt 4,2025-08-15 00:30:00,Running,NaN,1503.22,0.06,77.307,96.755,1.21,314.38,58.20,15.03,384.20,1.57925,85.781
3,Conveyor Belt 4,2025-08-15 00:45:00,Running,NaN,1508.11,0.04,77.474,97.661,1.29,311.84,56.16,15.43,379.79,1.57900,85.708
4,Conveyor Belt 4,2025-08-15 01:00:00,Running,NaN,1498.13,0.06,77.785,97.471,1.07,317.14,55.39,14.35,383.95,1.57875,85.635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26204,Conveyor Belt 4,2026-05-13 23:00:00,Running,NaN,1502.84,0.05,76.119,95.287,1.39,305.42,62.72,15.93,377.00,1.63700,68.610
26205,Conveyor Belt 4,2026-05-13 23:15:00,Running,NaN,1503.36,0.05,75.889,95.888,1.06,312.37,64.70,14.28,377.08,1.63675,68.537
26206,Conveyor Belt 4,2026-05-13 23:30:00,Running,NaN,1498.34,0.04,76.001,95.738,1.28,287.36,57.81,15.42,384.19,1.63650,68.464
26207,Conveyor Belt 4,2026-05-13 23:45:00,Running,NaN,1495.26,0.05,76.106,95.848,1.30,297.35,58.84,15.49,376.62,1.63625,68.391
26208,Conveyor Belt 4,2026-05-14 00:00:00,Running,NaN,1490.82,0.04,77.130,96.902,1.36,318.07,55.12,15.79,382.09,1.58000,68.318

In [46]:
# Convert datetime to numeric (Unix timestamp in seconds)
df['date_numeric'] = pd.to_datetime(df['Timestamp']).astype('int64') // 10**9 #seconds 
df

,Name,Timestamp,Status,Description,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition,date_numeric
0,Conveyor Belt 4,2025-08-15 00:00:00,Running,NaN,1490.82,0.04,77.130,96.902,1.36,318.07,55.12,15.79,382.09,1.58000,86.000,1755216000
1,Conveyor Belt 4,2025-08-15 00:15:00,Running,NaN,1498.37,0.04,77.076,96.975,1.07,295.50,59.68,14.34,376.48,1.57950,85.854,1755216900
2,Conveyor Belt 4,2025-08-15 00:30:00,Running,NaN,1503.22,0.06,77.307,96.755,1.21,314.38,58.20,15.03,384.20,1.57925,85.781,1755217800
3,Conveyor Belt 4,2025-08-15 00:45:00,Running,NaN,1508.11,0.04,77.474,97.661,1.29,311.84,56.16,15.43,379.79,1.57900,85.708,1755218700
4,Conveyor Belt 4,2025-08-15 01:00:00,Running,NaN,1498.13,0.06,77.785,97.471,1.07,317.14,55.39,14.35,383.95,1.57875,85.635,1755219600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26204,Conveyor Belt 4,2026-05-13 23:00:00,Running,NaN,1502.84,0.05,76.119,95.287,1.39,305.42,62.72,15.93,377.00,1.63700,68.610,1778713200
26205,Conveyor Belt 4,2026-05-13 23:15:00,Running,NaN,1503.36,0.05,75.889,95.888,1.06,312.37,64.70,14.28,377.08,1.63675,68.537,1778714100
26206,Conveyor Belt 4,2026-05-13 23:30:00,Running,NaN,1498.34,0.04,76.001,95.738,1.28,287.36,57.81,15.42,384.19,1.63650,68.464,1778715000
26207,Conveyor Belt 4,2026-05-13 23:45:00,Running,NaN,1495.26,0.05,76.106,95.848,1.30,297.35,58.84,15.49,376.62,1.63625,68.391,1778715900
26208,Conveyor Belt 4,2026-05-14 00:00:00,Running,NaN,1490.82,0.04,77.130,96.902,1.36,318.07,55.12,15.79,382.09,1.58000,68.318,1778716800

In [47]:
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import MinMaxScaler


train_cols = [
    "Vibration Frequency",
    "Vibration Amplitude",
    "Bearing Temperature",
    "Motor Temperature",
    "Belt Load",
    "Torque",
    "Noise Levels",
    "Current and Voltage",
    "Hydraulic Pressure",
    "Belt Thickness",
    "Roller Condition",  # Removed due to -1 correlation
]

# Select features and target variable
X = df[train_cols]

# Initialize MinMaxScaler Use to normalize all X values so they are all around similar ranges to improve model performance
# Note, assuming all metrics are linear and not logarithmic for now
min_max_scaler = MinMaxScaler()

# Fit and transform the feature data
X_scaled = min_max_scaler.fit_transform(X)

y = df['date_numeric']

# Scale the target variable to be normalized for similar reasons
y_scaled = min_max_scaler.fit_transform(y.values.reshape(-1, 1))

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

# Initialize LGBMRegressor
lgbm_reg = lgb.LGBMRegressor(objective='regression', random_state=42)

# Train the model
lgbm_reg.fit(X_train, y_train)

# Predict on the test set
y_pred = lgbm_reg.predict(X_test)

# Evaluate model performance
r2 = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f"Light gradient boost RÂ² Score: {r2:.4f}")
print(f"LGBM RMSE: {rmse:.4f}")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000971 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1819
[LightGBM] [Info] Number of data points in the train set: 20890, number of used features: 11
[LightGBM] [Info] Start training from score 0.500069
Light gradient boost RÂ² Score: -0.0040
LGBM RMSE: 0.2894

/home/aniemcz/.conda/envs/universal/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/aniemcz/.conda/envs/universal/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [48]:
X_scaled = pd.DataFrame(X_scaled, columns=train_cols)
X_scaled

,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition
0,0.222872,0.00,0.648483,0.870788,0.900,0.958701,0.295867,0.653759,0.540007,0.325843,0.592632
1,0.406974,0.00,0.647445,0.874549,0.175,0.390330,0.461204,0.323462,0.444501,0.323034,0.588384
2,0.525238,0.50,0.651882,0.863215,0.525,0.865777,0.407542,0.480638,0.575928,0.321629,0.586260
3,0.644477,0.00,0.655090,0.909892,0.725,0.801813,0.333575,0.571754,0.500851,0.320225,0.584136
4,0.401122,0.50,0.661064,0.900103,0.175,0.935281,0.305656,0.325740,0.571672,0.318820,0.582012
...,...,...,...,...,...,...,...,...,...,...,...
26108,0.515972,0.25,0.629063,0.787584,0.975,0.640141,0.571429,0.685649,0.453354,0.646067,0.086624
26109,0.528652,0.25,0.624645,0.818547,0.150,0.815160,0.643220,0.309795,0.454716,0.644663,0.084500
26110,0.406242,0.00,0.626796,0.810819,0.700,0.185344,0.393401,0.569476,0.575758,0.643258,0.082376
26111,0.331139,0.25,0.628813,0.816486,0.750,0.436918,0.430747,0.585421,0.446885,0.641854,0.080251
26112,0.222872,0.00,0.648483,0.870788,0.900,0.958701,0.295867,0.653759,0.540007,0.325843,0.078127

In [14]:
df_test = pd.read_excel('Test/Belt 1 Test Data.xlsx', header=None)
df_test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Conveyor Belt 4,2026-05-14 00:15:00,Running,NaN,1498.37,0.04,77.076,96.975,1.07,295.50,59.68,14.34,376.48,1.54675,68.245
1,Conveyor Belt 4,2026-05-14 00:30:00,Running,NaN,1503.22,0.06,77.307,96.755,1.21,314.38,58.20,15.03,384.20,1.54650,68.172
2,Conveyor Belt 4,2026-05-14 00:45:00,Running,NaN,1508.11,0.04,77.474,97.661,1.29,311.84,56.16,15.43,379.79,1.54625,68.099
3,Conveyor Belt 4,2026-05-14 01:00:00,Running,NaN,1498.13,0.06,77.785,97.471,1.07,317.14,55.39,14.35,383.95,1.54600,68.026
4,Conveyor Belt 4,2026-05-14 01:15:00,Running,NaN,1494.89,0.05,77.813,97.814,1.33,305.58,62.25,15.65,383.02,1.54575,67.953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,Conveyor Belt 4,2026-05-28 22:45:00,Running,NaN,1515.67,0.05,75.549,95.590,1.25,309.20,55.44,15.23,384.42,1.68175,68.683
1435,Conveyor Belt 4,2026-05-28 23:00:00,Running,NaN,1502.84,0.05,76.119,95.287,1.39,305.42,62.72,14.67,377.00,1.68150,68.610
1436,Conveyor Belt 4,2026-05-28 23:15:00,Running,NaN,1503.36,0.05,75.889,95.888,1.06,312.37,64.70,14.69,377.08,1.68125,68.537
1437,Conveyor Belt 4,2026-05-28 23:30:00,Running,NaN,1498.34,0.04,76.001,95.738,1.28,287.36,57.81,16.03,384.19,1.68100,68.464
1438,Conveyor Belt 4,2026-05-28 23:45:00,Running,NaN,1495.26,0.05,76.106,95.848,1.30,297.35,58.84,15.49,376.62,1.68075,68.391

In [15]:
df_test.iloc[:, 4:14]

,4,5,6,7,8,9,10,11,12,13
0,1498.37,0.04,77.076,96.975,1.07,295.50,59.68,14.34,376.48,1.54675
1,1503.22,0.06,77.307,96.755,1.21,314.38,58.20,15.03,384.20,1.54650
2,1508.11,0.04,77.474,97.661,1.29,311.84,56.16,15.43,379.79,1.54625
3,1498.13,0.06,77.785,97.471,1.07,317.14,55.39,14.35,383.95,1.54600
4,1494.89,0.05,77.813,97.814,1.33,305.58,62.25,15.65,383.02,1.54575
...,...,...,...,...,...,...,...,...,...,...
1434,1515.67,0.05,75.549,95.590,1.25,309.20,55.44,15.23,384.42,1.68175
1435,1502.84,0.05,76.119,95.287,1.39,305.42,62.72,14.67,377.00,1.68150
1436,1503.36,0.05,75.889,95.888,1.06,312.37,64.70,14.69,377.08,1.68125
1437,1498.34,0.04,76.001,95.738,1.28,287.36,57.81,16.03,384.19,1.68100
1438,1495.26,0.05,76.106,95.848,1.30,297.35,58.84,15.49,376.62,1.68075

In [16]:
columns_dict = dict(zip(range(4, 15), train_cols))
df_test = df_test.rename(columns=columns_dict)
df_test

,0,1,2,3,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition
0,Conveyor Belt 4,2026-05-14 00:15:00,Running,NaN,1498.37,0.04,77.076,96.975,1.07,295.50,59.68,14.34,376.48,1.54675,68.245
1,Conveyor Belt 4,2026-05-14 00:30:00,Running,NaN,1503.22,0.06,77.307,96.755,1.21,314.38,58.20,15.03,384.20,1.54650,68.172
2,Conveyor Belt 4,2026-05-14 00:45:00,Running,NaN,1508.11,0.04,77.474,97.661,1.29,311.84,56.16,15.43,379.79,1.54625,68.099
3,Conveyor Belt 4,2026-05-14 01:00:00,Running,NaN,1498.13,0.06,77.785,97.471,1.07,317.14,55.39,14.35,383.95,1.54600,68.026
4,Conveyor Belt 4,2026-05-14 01:15:00,Running,NaN,1494.89,0.05,77.813,97.814,1.33,305.58,62.25,15.65,383.02,1.54575,67.953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,Conveyor Belt 4,2026-05-28 22:45:00,Running,NaN,1515.67,0.05,75.549,95.590,1.25,309.20,55.44,15.23,384.42,1.68175,68.683
1435,Conveyor Belt 4,2026-05-28 23:00:00,Running,NaN,1502.84,0.05,76.119,95.287,1.39,305.42,62.72,14.67,377.00,1.68150,68.610
1436,Conveyor Belt 4,2026-05-28 23:15:00,Running,NaN,1503.36,0.05,75.889,95.888,1.06,312.37,64.70,14.69,377.08,1.68125,68.537
1437,Conveyor Belt 4,2026-05-28 23:30:00,Running,NaN,1498.34,0.04,76.001,95.738,1.28,287.36,57.81,16.03,384.19,1.68100,68.464
1438,Conveyor Belt 4,2026-05-28 23:45:00,Running,NaN,1495.26,0.05,76.106,95.848,1.30,297.35,58.84,15.49,376.62,1.68075,68.391

In [17]:
X_test_new = df_test[train_cols]

# Predict using trained XGBoost model
y_pred_new = lgbm_reg.predict(X_test_new)

print(len(y_pred_new))

1439

In [18]:
import pandas as pd
from sklearn.metrics import r2_score

# Convert datetime to numeric (Unix timestamp in seconds)
df_test[1] = df_test[1].astype('int64') // 10**9  # Convert ns to seconds

# Assuming df_test is your test DataFrame and column 1 (index 1) is the target variable
y_actual = df_test[1] # Extract column 1 (actual values)

# Your existing code
X_test_new = df_test[train_cols]
y_pred_new = xgb_reg.predict(X_test_new)

# Calculate RÂ² score
r2 = r2_score(y_actual, y_pred_new)

# Print results
print("Predictions:", y_pred_new)
print("Actual values:", y_actual.values)
print("RÂ² Score:", r2)

Predictions: [1.7670346e+09 1.7669431e+09 1.7674533e+09 ... 1.7681038e+09 1.7665495e+09
 1.7695919e+09]
Actual values: [1778717700 1778718600 1778719500 ... 1780010100 1780011000 1780011900]
RÂ² Score: -939.8906860351562

In [19]:
y_pred_new[0]

1767034600.0

In [20]:
y_actual[0]

1778717700

In [87]:
# Normalize Data

-6456.747777777778