In [116]:
import pandas as pd

In [117]:
# Load the dataset
df = pd.read_excel('Train/Belt 1 9 Months negative data.xlsx')
df

,Name,Timestamp,Status,Description,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition
0,Conveyor Belt 4,2025-08-15 00:00:00,Running,NaN,1490.82,0.04,77.13,96.90,1.36,318.07,55.12,15.79,382.09,1.58,86.00
1,Conveyor Belt 4,2025-08-15 00:15:00,Running,NaN,1498.37,0.04,77.08,96.97,1.07,295.50,59.68,14.34,376.48,1.58,85.85
2,Conveyor Belt 4,2025-08-15 00:30:00,Running,NaN,1503.22,0.06,77.31,96.75,1.21,314.38,58.20,15.03,384.20,1.58,85.78
3,Conveyor Belt 4,2025-08-15 00:45:00,Running,NaN,1508.11,0.04,77.47,97.66,1.29,311.84,56.16,15.43,379.79,1.58,85.71
4,Conveyor Belt 4,2025-08-15 01:00:00,Running,NaN,1498.13,0.06,77.78,97.47,1.07,317.14,55.39,14.35,383.95,1.58,85.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26204,Conveyor Belt 4,2026-05-13 23:00:00,Running,NaN,1502.84,0.05,76.12,95.29,1.39,305.42,62.72,15.93,377.00,1.64,68.61
26205,Conveyor Belt 4,2026-05-13 23:15:00,Running,NaN,1503.36,0.05,75.89,95.89,1.06,312.37,64.70,14.28,377.08,1.64,68.54
26206,Conveyor Belt 4,2026-05-13 23:30:00,Running,NaN,1498.34,0.04,76.00,95.74,1.28,287.36,57.81,15.42,384.19,1.64,68.46
26207,Conveyor Belt 4,2026-05-13 23:45:00,Running,NaN,1495.26,0.05,76.11,95.85,1.30,297.35,58.84,15.49,376.62,1.64,68.39
26208,Conveyor Belt 4,2026-05-14 00:00:00,Running,NaN,1490.82,0.04,77.13,96.90,1.36,318.07,55.12,15.79,382.09,1.58,68.32

In [118]:
# Convert 'Timestamp' to datetime, invalid dates will be set to NaT
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce') 

# Drop rows where the 'Timestamp' is NaT (invalid date)
df.dropna(subset=['Timestamp'], inplace=True)

df

,Name,Timestamp,Status,Description,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition
0,Conveyor Belt 4,2025-08-15 00:00:00,Running,NaN,1490.82,0.04,77.13,96.90,1.36,318.07,55.12,15.79,382.09,1.58,86.00
1,Conveyor Belt 4,2025-08-15 00:15:00,Running,NaN,1498.37,0.04,77.08,96.97,1.07,295.50,59.68,14.34,376.48,1.58,85.85
2,Conveyor Belt 4,2025-08-15 00:30:00,Running,NaN,1503.22,0.06,77.31,96.75,1.21,314.38,58.20,15.03,384.20,1.58,85.78
3,Conveyor Belt 4,2025-08-15 00:45:00,Running,NaN,1508.11,0.04,77.47,97.66,1.29,311.84,56.16,15.43,379.79,1.58,85.71
4,Conveyor Belt 4,2025-08-15 01:00:00,Running,NaN,1498.13,0.06,77.78,97.47,1.07,317.14,55.39,14.35,383.95,1.58,85.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26204,Conveyor Belt 4,2026-05-13 23:00:00,Running,NaN,1502.84,0.05,76.12,95.29,1.39,305.42,62.72,15.93,377.00,1.64,68.61
26205,Conveyor Belt 4,2026-05-13 23:15:00,Running,NaN,1503.36,0.05,75.89,95.89,1.06,312.37,64.70,14.28,377.08,1.64,68.54
26206,Conveyor Belt 4,2026-05-13 23:30:00,Running,NaN,1498.34,0.04,76.00,95.74,1.28,287.36,57.81,15.42,384.19,1.64,68.46
26207,Conveyor Belt 4,2026-05-13 23:45:00,Running,NaN,1495.26,0.05,76.11,95.85,1.30,297.35,58.84,15.49,376.62,1.64,68.39
26208,Conveyor Belt 4,2026-05-14 00:00:00,Running,NaN,1490.82,0.04,77.13,96.90,1.36,318.07,55.12,15.79,382.09,1.58,68.32

In [119]:
# Convert datetime to numeric (Unix timestamp in seconds)
df['date_numeric'] = pd.to_datetime(df['Timestamp']).astype('int64') // 10**9 #seconds 
df

,Name,Timestamp,Status,Description,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition,date_numeric
0,Conveyor Belt 4,2025-08-15 00:00:00,Running,NaN,1490.82,0.04,77.13,96.90,1.36,318.07,55.12,15.79,382.09,1.58,86.00,1755216000
1,Conveyor Belt 4,2025-08-15 00:15:00,Running,NaN,1498.37,0.04,77.08,96.97,1.07,295.50,59.68,14.34,376.48,1.58,85.85,1755216900
2,Conveyor Belt 4,2025-08-15 00:30:00,Running,NaN,1503.22,0.06,77.31,96.75,1.21,314.38,58.20,15.03,384.20,1.58,85.78,1755217800
3,Conveyor Belt 4,2025-08-15 00:45:00,Running,NaN,1508.11,0.04,77.47,97.66,1.29,311.84,56.16,15.43,379.79,1.58,85.71,1755218700
4,Conveyor Belt 4,2025-08-15 01:00:00,Running,NaN,1498.13,0.06,77.78,97.47,1.07,317.14,55.39,14.35,383.95,1.58,85.64,1755219600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26204,Conveyor Belt 4,2026-05-13 23:00:00,Running,NaN,1502.84,0.05,76.12,95.29,1.39,305.42,62.72,15.93,377.00,1.64,68.61,1778713200
26205,Conveyor Belt 4,2026-05-13 23:15:00,Running,NaN,1503.36,0.05,75.89,95.89,1.06,312.37,64.70,14.28,377.08,1.64,68.54,1778714100
26206,Conveyor Belt 4,2026-05-13 23:30:00,Running,NaN,1498.34,0.04,76.00,95.74,1.28,287.36,57.81,15.42,384.19,1.64,68.46,1778715000
26207,Conveyor Belt 4,2026-05-13 23:45:00,Running,NaN,1495.26,0.05,76.11,95.85,1.30,297.35,58.84,15.49,376.62,1.64,68.39,1778715900
26208,Conveyor Belt 4,2026-05-14 00:00:00,Running,NaN,1490.82,0.04,77.13,96.90,1.36,318.07,55.12,15.79,382.09,1.58,68.32,1778716800

In [120]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


train_cols = [
    "Vibration Frequency",
    "Vibration Amplitude",
    "Bearing Temperature",
    "Motor Temperature",
    "Belt Load",
    "Torque",
    "Noise Levels",
    "Current and Voltage",
    "Hydraulic Pressure",
    "Belt Thickness",
    "Roller Condition",  # Removed due to -1 correlation
]

# Select features and target variable
X = df[train_cols]

y = df['date_numeric']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost Regressor
xgb_reg = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, random_state=42)

# Train the model
xgb_reg.fit(X_train, y_train)

# Make predictions
y_pred = xgb_reg.predict(X_test)

# Evaluate model performance
r2 = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f"XGBoost RÂ² Score: {r2:.4f}")
print(f"XGBoost RMSE: {rmse:.4f}")

XGBoost RÂ² Score: -0.0675
XGBoost RMSE: 7012912.5168

In [77]:
df_test = pd.read_excel('Belt 1 Test Data.xlsx', header=None)
df_test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Conveyor Belt 4,2026-05-14 00:15:00,Running,NaN,1498.37,0.04,77.08,96.97,1.07,295.50,59.68,14.34,376.48,1.55,68.25
1,Conveyor Belt 4,2026-05-14 00:30:00,Running,NaN,1503.22,0.06,77.31,96.75,1.21,314.38,58.20,15.03,384.20,1.55,68.17
2,Conveyor Belt 4,2026-05-14 00:45:00,Running,NaN,1508.11,0.04,77.47,97.66,1.29,311.84,56.16,15.43,379.79,1.55,68.10
3,Conveyor Belt 4,2026-05-14 01:00:00,Running,NaN,1498.13,0.06,77.78,97.47,1.07,317.14,55.39,14.35,383.95,1.55,68.03
4,Conveyor Belt 4,2026-05-14 01:15:00,Running,NaN,1494.89,0.05,77.81,97.81,1.33,305.58,62.25,15.65,383.02,1.55,67.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,Conveyor Belt 4,2026-05-28 22:45:00,Running,NaN,1515.67,0.05,75.55,95.59,1.25,309.20,55.44,15.23,384.42,1.68,68.68
1435,Conveyor Belt 4,2026-05-28 23:00:00,Running,NaN,1502.84,0.05,76.12,95.29,1.39,305.42,62.72,14.67,377.00,1.68,68.61
1436,Conveyor Belt 4,2026-05-28 23:15:00,Running,NaN,1503.36,0.05,75.89,95.89,1.06,312.37,64.70,14.69,377.08,1.68,68.54
1437,Conveyor Belt 4,2026-05-28 23:30:00,Running,NaN,1498.34,0.04,76.00,95.74,1.28,287.36,57.81,16.03,384.19,1.68,68.46
1438,Conveyor Belt 4,2026-05-28 23:45:00,Running,NaN,1495.26,0.05,76.11,95.85,1.30,297.35,58.84,15.49,376.62,1.68,68.39

In [78]:
df_test.iloc[:, 4:14]

          4    5     6     7    8      9     10    11     12   13
0    1498.37 0.04 77.08 96.97 1.07 295.50 59.68 14.34 376.48 1.55
1    1503.22 0.06 77.31 96.75 1.21 314.38 58.20 15.03 384.20 1.55
2    1508.11 0.04 77.47 97.66 1.29 311.84 56.16 15.43 379.79 1.55
3    1498.13 0.06 77.78 97.47 1.07 317.14 55.39 14.35 383.95 1.55
4    1494.89 0.05 77.81 97.81 1.33 305.58 62.25 15.65 383.02 1.55
...      ...  ...   ...   ...  ...    ...   ...   ...    ...  ...
1434 1515.67 0.05 75.55 95.59 1.25 309.20 55.44 15.23 384.42 1.68
1435 1502.84 0.05 76.12 95.29 1.39 305.42 62.72 14.67 377.00 1.68
1436 1503.36 0.05 75.89 95.89 1.06 312.37 64.70 14.69 377.08 1.68
1437 1498.34 0.04 76.00 95.74 1.28 287.36 57.81 16.03 384.19 1.68
1438 1495.26 0.05 76.11 95.85 1.30 297.35 58.84 15.49 376.62 1.68

[1439 rows x 10 columns]

In [79]:
columns_dict = dict(zip(range(4, 15), train_cols))
df_test = df_test.rename(columns=columns_dict)
df_test

,0,1,2,3,Vibration Frequency,Vibration Amplitude,Bearing Temperature,Motor Temperature,Belt Load,Torque,Noise Levels,Current and Voltage,Hydraulic Pressure,Belt Thickness,Roller Condition
0,Conveyor Belt 4,2026-05-14 00:15:00,Running,NaN,1498.37,0.04,77.08,96.97,1.07,295.50,59.68,14.34,376.48,1.55,68.25
1,Conveyor Belt 4,2026-05-14 00:30:00,Running,NaN,1503.22,0.06,77.31,96.75,1.21,314.38,58.20,15.03,384.20,1.55,68.17
2,Conveyor Belt 4,2026-05-14 00:45:00,Running,NaN,1508.11,0.04,77.47,97.66,1.29,311.84,56.16,15.43,379.79,1.55,68.10
3,Conveyor Belt 4,2026-05-14 01:00:00,Running,NaN,1498.13,0.06,77.78,97.47,1.07,317.14,55.39,14.35,383.95,1.55,68.03
4,Conveyor Belt 4,2026-05-14 01:15:00,Running,NaN,1494.89,0.05,77.81,97.81,1.33,305.58,62.25,15.65,383.02,1.55,67.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,Conveyor Belt 4,2026-05-28 22:45:00,Running,NaN,1515.67,0.05,75.55,95.59,1.25,309.20,55.44,15.23,384.42,1.68,68.68
1435,Conveyor Belt 4,2026-05-28 23:00:00,Running,NaN,1502.84,0.05,76.12,95.29,1.39,305.42,62.72,14.67,377.00,1.68,68.61
1436,Conveyor Belt 4,2026-05-28 23:15:00,Running,NaN,1503.36,0.05,75.89,95.89,1.06,312.37,64.70,14.69,377.08,1.68,68.54
1437,Conveyor Belt 4,2026-05-28 23:30:00,Running,NaN,1498.34,0.04,76.00,95.74,1.28,287.36,57.81,16.03,384.19,1.68,68.46
1438,Conveyor Belt 4,2026-05-28 23:45:00,Running,NaN,1495.26,0.05,76.11,95.85,1.30,297.35,58.84,15.49,376.62,1.68,68.39

In [80]:
X_test_new = df_test[train_cols]

# Predict using trained XGBoost model
y_pred_new = xgb_reg.predict(X_test_new)

print(len(y_pred_new))

1439

In [81]:
import pandas as pd
from sklearn.metrics import r2_score

# Convert datetime to numeric (Unix timestamp in seconds)
df_test[1] = df_test[1].astype('int64') // 10**9  # Convert ns to seconds

# Assuming df_test is your test DataFrame and column 1 (index 1) is the target variable
y_actual = df_test[1] # Extract column 1 (actual values)

# Your existing code
X_test_new = df_test[train_cols]
y_pred_new = xgb_reg.predict(X_test_new)

# Calculate RÂ² score
r2 = r2_score(y_actual, y_pred_new)

# Print results
print("Predictions:", y_pred_new)
print("Actual values:", y_actual.values)
print("RÂ² Score:", r2)

Predictions: [1.7554734e+09 1.7554729e+09 1.7554730e+09 ... 1.7554708e+09 1.7554728e+09
 1.7554732e+09]
Actual values: [1778717700 1778718600 1778719500 ... 1780010100 1780011000 1780011900]
RÂ² Score: -4143.59033203125

In [83]:
y_pred_new[0]

1755473400.0

In [84]:
y_actual[0]

1778717700

In [87]:
# Normalize Data

-6456.747777777778